//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1505_5_1_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<decimal> Avg_Grade { get; set; }
        public Nullable<int> Num_Of_Students { get; set; }
        public Nullable<int> Highest_Grade { get; set; }
    }
}
