//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1505_5_1_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int Course_ID { get; set; }
        public int Student_ID { get; set; }
        public Nullable<int> Grades1 { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
